/* Bundle the in-browser sandbox: evo/{allowlist,patch,sandbox.browser}.js →
   evo/sandbox.bundle.js (one IIFE on window). The source stays clean
   CommonJS for the Node CLI; this is the browser artifact for the no-build
   static site.  Run: node evo/build-sandbox.mjs   (or npm run evo:sandbox-build) */
import * as esbuild from 'esbuild';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const HERE = dirname(fileURLToPath(import.meta.url));
const out = join(HERE, 'sandbox.bundle.js');

const r = await esbuild.build({
  entryPoints: [join(HERE, 'sandbox-browser-entry.js')],
  bundle: true,
  outfile: out,
  format: 'iife',
  platform: 'browser',
  target: ['es2019'],
  logLevel: 'info',
  metafile: true,
  banner: { js: '/* GENERATED by evo/build-sandbox.mjs — bundles evo/{allowlist,patch,sandbox.browser}.js. Do not edit by hand. */' },
});
const bytes = Object.values(r.metafile.outputs).reduce((a, o) => a + o.bytes, 0);
console.log(`✓ wrote evo/sandbox.bundle.js (${(bytes / 1024).toFixed(0)} KB)`);
