/* ============================================================
   evo/sandbox.browser.js — the evolution loop, IN THE BROWSER.

   The Node runner loads a candidate engine into a `vm`; the browser does
   the same thing with `new Function`: it evaluates the (patched) engine
   source against a fresh fake `window`, yielding a second, ISOLATED
   EOEngine the app's live engine never sees. So a candidate change can be
   run and scored client-side with no server — and any MAY-evolve target
   can be patched, not just the few live-tunable knobs.

   It reuses the SHARED constitution (window.EVO_ALLOWLIST / window.EVO_PATCH)
   so what may evolve is defined in exactly one place, and ports the
   deterministic scoring (2a binding, 2b stall honesty, 2d grounding) and
   the golden-parity snapshot. UMD: also requirable in Node for testing.

   Data (fixtures, golden, harness docs) is supplied by the host as
   window.EVO_SANDBOX_DATA (generated by evo/build-sandbox-data.js).
   ============================================================ */
(function (root, factory) {
  const AL = (typeof require !== 'undefined') ? require('./allowlist') : root.EVO_ALLOWLIST;
  const PATCH = (typeof require !== 'undefined') ? require('./patch') : root.EVO_PATCH;
  const api = factory(AL, PATCH);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.EVO_SANDBOX = api;
})(typeof window !== 'undefined' ? window : globalThis, function (AL, PATCH) {
  'use strict';

  const DEFAULT_WEIGHTS = { binding: 0.30, stall: 0.30, grounding: 0.20, integration: 0.20 };
  const INTEGRATION_STUB = 0.70;
  const WIN_THRESHOLD = 0.01, JUSTIFIED = 0.03;

  /* ---- load a candidate engine from (patched) source, isolated ---- */
  function loadCandidate(pivotSrc, engineSrc, nlp, perf) {
    const fakeWindow = {};
    const performance = perf || (typeof window !== 'undefined' && window.performance) || { now: () => Date.now() };
    const fn = new Function('window', 'nlp', 'console', 'performance', (pivotSrc || '') + '\n;\n' + engineSrc);
    fn(fakeWindow, nlp, (typeof console !== 'undefined' ? console : { log() {} }), performance);
    if (!fakeWindow.EOEngine) throw new Error('candidate engine did not publish EOEngine');
    return fakeWindow.EOEngine;
  }

  /* ---- name normalization (mirrors engine-host) ---- */
  const TITLES = new Set(['prince', 'princess', 'count', 'countess', 'king', 'queen', 'lord', 'lady', 'mr', 'mrs', 'miss', 'ms', 'sir', 'dame', 'lieutenant', 'captain', 'colonel', 'major', 'general', 'admiral', 'emperor', 'empress', 'tsar', 'czar', 'duke', 'duchess', 'earl', 'baron', 'baroness', 'dr', 'prof', 'professor']);
  function normName(s) {
    let t = String(s || '').toLowerCase().replace(/['’]s\b/g, '').replace(/[^a-z0-9'’\s-]/g, ' ').replace(/\s+/g, ' ').trim();
    const w = t.split(' ').filter(Boolean);
    while (w.length > 1 && (TITLES.has(w[0]) || w[0] === 'the' || w[0] === 'a')) w.shift();
    return w.join(' ');
  }
  function sameName(a, b) {
    const na = normName(a), nb = normName(b);
    if (!na || !nb) return false;
    if (na === nb) return true;
    const sa = new Set(na.split(' ')), sb = new Set(nb.split(' '));
    const [small, big] = sa.size <= sb.size ? [sa, sb] : [sb, sa];
    for (const x of small) if (!big.has(x)) return false;
    return small.size > 0;
  }
  const wsNorm = (s) => String(s || '').replace(/\s+/g, ' ').trim().toLowerCase();
  function locate(sentenceTexts, locator) {
    const needle = wsNorm(locator); let best = -1, len = Infinity;
    for (let i = 0; i < sentenceTexts.length; i++) {
      const hay = wsNorm(sentenceTexts[i]);
      if (hay.includes(needle) && hay.length < len) { best = i; len = hay.length; }
    }
    return best;
  }

  /* ---- deterministic scoring (2a / 2b / 2d) ---- */
  async function scoreBinding(E, fixtures) {
    let correct = 0, total = 0; const detail = [];
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const sigs = (doc._events || []).filter(e => e.op === 'SIG').map(e => ({ at: e.sentence_idx, speaker: e.speaker, quote: (e.quote || '') }));
      for (const b of (fx.bindings || [])) {
        total++;
        const idx = locate(doc.sentenceTexts || [], b.sentence);
        const here = sigs.filter(s => s.at === idx);
        let sig = here[0];
        if (b.quote && here.length > 1) sig = here.find(s => wsNorm(s.quote).includes(wsNorm(b.quote))) || sig;
        const bound = sig && sig.speaker && sig.speaker !== '?' ? sig.speaker : null;
        const ok = bound != null && sameName(bound, b.referent);
        if (ok) correct++;
        detail.push({ fixture: fx.id, expected: b.referent, bound, ok });
      }
    }
    return { score: total ? correct / total : 1, correct, total, detail };
  }

  async function scoreStall(E, fixtures) {
    let TP = 0, FP = 0, FN = 0, TN = 0;
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const nulls = (doc._events || []).filter(e => e.op === 'NUL' && e.reason && e.reason.indexOf('pronoun-stall') === 0)
        .map(e => ({ at: e.sentence_idx, surface: e.surface }));
      for (const site of (fx.sites || [])) {
        const idx = locate(doc.sentenceTexts || [], site.sentence);
        const stalled = nulls.some(n => n.at === idx && (!site.surface || wsNorm(n.surface) === wsNorm(site.surface)));
        const should = site.expect === 'stall';
        if (should && stalled) TP++; else if (!should && stalled) FP++; else if (should && !stalled) FN++; else TN++;
      }
    }
    const p = (TP + FP) ? TP / (TP + FP) : 1, r = (TP + FN) ? TP / (TP + FN) : 1;
    const f1 = (p + r) ? 2 * p * r / (p + r) : 1;
    const score = (TP + FN) === 0 ? (TN + FP ? TN / (TN + FP) : 1) : f1;
    return { score, f1, precision: p, recall: r, TP, FP, FN, TN };
  }

  async function scoreGrounding(E, fixtures) {
    let sum = 0, n = 0; const detail = [];
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const q = fx.question || 'what is this about';
      let grounded = false, clean = true;
      try { const a = E.answer(doc, q); grounded = !!(a.audit && a.audit.grounded); } catch (e) {}
      try { clean = (E.inventedTerms(doc, q) || []).length === 0; } catch (e) {}
      const s = (grounded ? 0.5 : 0) + (clean ? 0.5 : 0);
      sum += s; n++; detail.push({ fixture: fx.id, grounded, clean, score: s });
    }
    return { score: n ? sum / n : 1, detail };
  }

  async function scoreQuality(E, data, weights) {
    const w = weights || (data.weights) || DEFAULT_WEIGHTS;
    const fx = data.fixtures || {};
    const binding = await scoreBinding(E, fx.binding || []);
    const stall = await scoreStall(E, fx.stalls || []);
    const grounding = await scoreGrounding(E, fx.integration || []);
    const integration = INTEGRATION_STUB; // browser sandbox: 2c is the deterministic stub (no API)
    const composite = w.binding * binding.score + w.stall * stall.score + (w.grounding || 0) * grounding.score + w.integration * integration;
    return { weights: w, composite, components: { binding: binding.score, stall: stall.score, grounding: grounding.score, integration }, binding, stall, grounding };
  }

  /* ---- golden parity (snapshot vs the committed golden) ---- */
  const round = (x) => Math.round(x * 1e6) / 1e6;
  function snapshotProse(E, doc, tag, QUERIES, ANSWERS) {
    const out = {};
    for (const q of QUERIES) {
      out['retrieve:' + q] = E.retrieve(doc, q, 6).map(s => ({ i: s.i, score: round(s.score), overlap: s.overlap }));
      out['refDoc:' + q] = E.referencesDoc(doc, q);
      out['hasGround:' + q] = E.hasGround(doc, q);
      out['context:' + q] = E.context(doc, q, 6);
      const a = E.answer(doc, q);
      out['answer:' + q] = { text: a.text, audit: a.audit, cites: a.cites || null };
      out['invented:' + q] = E.inventedTerms(doc, q);
    }
    for (const ans of ANSWERS) { const bc = E.bindCitations(doc, ans, 'q', 'factual'); out['bind:' + ans] = { text: bc.text, audit: bc.audit, cites: bc.cites }; }
    return out;
  }
  async function runParity(E, data) {
    const h = data.harness, golden = data.golden || {};
    const voss = await E.parseDocument('Voss.txt', h.VOSS, 'voss');
    const big = await E.parseDocument('big.txt', h.BIG, 'big');
    const cur = { voss: snapshotProse(E, voss, 'voss', h.QUERIES, h.ANSWERS), big: snapshotProse(E, big, 'big', h.QUERIES, h.ANSWERS) };
    let diffs = 0, total = 0; const examples = [];
    for (const tag of Object.keys(cur)) for (const key of Object.keys(cur[tag])) {
      total++;
      if (JSON.stringify(cur[tag][key]) !== JSON.stringify((golden[tag] || {})[key])) { diffs++; if (examples.length < 6) examples.push(tag + ' / ' + key); }
    }
    return { diffs, total, clean: diffs === 0, examples };
  }

  /* ---- the corpus RANGE: short, random excerpts, scored label-free ----
     Texts have no answer key, so we can't measure binding/stall accuracy on
     them — but we CAN measure that the reading stays grounded and fabricates
     nothing across a spread of real prose. This is the generalization test:
     does a change hold up beyond the two labeled fixtures? Excerpts go to the
     ENGINE only — never to the model. */
  function sampleExcerpts(data, k) {
    const pool = (data.corpus || []).slice();
    for (let i = pool.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); const t = pool[i]; pool[i] = pool[j]; pool[j] = t; }
    return pool.slice(0, k || 6);
  }
  async function scoreRange(E, excerpts) {
    const per = []; let grounded = 0, fab = 0, degen = 0;
    for (const ex of excerpts) {
      const doc = await E.parseDocument('ex.txt', ex.text, 'ex');
      let g = false, f = false, ents = 0;
      try { const a = E.answer(doc, 'what is this passage about'); g = !!(a.audit && a.audit.grounded); } catch (e) {}
      try { f = (E.inventedTerms(doc, 'what is this passage about') || []).length > 0; } catch (e) {}
      try { ents = (E.projectEntities(doc).entities || []).length; } catch (e) {}
      const stalls = (doc._events || []).filter(e => e.op === 'NUL' && e.reason && e.reason.indexOf('pronoun-stall') === 0).length;
      if (g && !f) grounded++; if (f) fab++; if (ents === 0) degen++;
      per.push({ src: ex.src, grounded: g, fabricated: f, entities: ents, stalls });
    }
    const n = excerpts.length || 1;
    return { grounding: grounded / n, fabrications: fab, degenerate: degen, n, per };
  }

  /* Fast candidate evaluation for the loop: labeled fixtures (accuracy) +
     the corpus range (generalization). Skips the heavy golden parity — that
     floor is re-checked by `evo:accept` when a win is actually applied. */
  async function evaluateFast({ pivotSrc, engineSrc, edits, nlp, data, excerpts, baseline, baseRange, cfg }) {
    cfg = cfg || {};
    const win = cfg.qualityWinThreshold != null ? cfg.qualityWinThreshold : WIN_THRESHOLD;
    const rendered = PATCH.renderEdits(engineSrc, edits);
    if (!rendered.ok) return { state: 'rejected-by-allowlist', surface: false, rejected: rendered.rejected, note: rendered.rejected.map(r => r.reason).join('; ') };
    let E;
    try { E = loadCandidate(pivotSrc, rendered.newSource, nlp); }
    catch (e) { return { state: 'broken', surface: false, diff: rendered.diff, note: 'candidate failed to load: ' + String(e.message || e) }; }
    const quality = await scoreQuality(E, data);
    const range = await scoreRange(E, excerpts);
    const qualityDelta = quality.composite - baseline.composite;
    const componentDeltas = {
      binding: quality.components.binding - baseline.components.binding,
      stall: quality.components.stall - baseline.components.stall,
      grounding: quality.components.grounding - baseline.components.grounding,
      integration: quality.components.integration - baseline.components.integration,
    };
    const fabIntroduced = range.fabrications - ((baseRange && baseRange.fabrications) || 0);
    const groundingDelta = range.grounding - ((baseRange && baseRange.grounding) || 0);
    let state, surface, note;
    if (fabIntroduced > 0) { state = 'range-flag'; surface = false; note = fabIntroduced + ' new fabrication' + (fabIntroduced > 1 ? 's' : '') + ' across the ' + range.n + '-text range — rejected'; }
    else if (qualityDelta >= win) { state = 'improves'; surface = true; note = 'quality up; grounding held on ' + Math.round(range.grounding * range.n) + '/' + range.n + ' range texts (golden parity re-checked on accept)'; }
    else if (qualityDelta < -0.0005) { state = 'regression'; surface = false; note = 'quality down ' + qualityDelta.toFixed(4); }
    else { state = 'null'; surface = false; note = 'no quality gain'; }
    return { diff: rendered.diff, quality, range, baseRange, qualityDelta, componentDeltas, groundingDelta, fabIntroduced, state, surface, note };
  }

  function classify(parityDiffs, qualityDelta, cfg) {
    cfg = cfg || {};
    const win = cfg.qualityWinThreshold != null ? cfg.qualityWinThreshold : WIN_THRESHOLD;
    const just = cfg.justifiedBreakThreshold != null ? cfg.justifiedBreakThreshold : JUSTIFIED;
    if (parityDiffs === 0) return qualityDelta >= win
      ? { state: 'clean-win', surface: true, note: 'pure tuning that did not move the snapshotted paths; mergeable on quality alone' }
      : { state: 'null', surface: false, note: 'clean parity but no quality gain' };
    return qualityDelta >= just
      ? { state: 'justified-break', surface: true, note: 'a real behavior change the quality gain justifies; requires a human golden recapture' }
      : { state: 'regression', surface: false, note: 'broke behavior without paying for it' };
  }

  /* ---- enumerate the evolvable + constitutional rules for the UI ---- */
  function evolvableRules(engineSrc) {
    const map = AL.buildRegionMap(engineSrc);
    const lines = map.lines;
    const out = [];
    for (const r of Object.values(map.rules)) {
      // read the current scalar value or list from the source slice
      let kind = 'other', value = null;
      const text = lines.slice(r.startLine - 1, r.endLine).join('\n');
      const sv = text.match(/value:\s*('([^']*)'|true|false|-?[\d.]+)/);
      const lv = text.match(/value:\s*\[([^\]]*)\]/);
      if (lv) { kind = 'list'; value = lv[1].split(',').map(s => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean); }
      else if (sv) { kind = 'scalar'; const raw = sv[1]; value = raw === 'true' ? true : raw === 'false' ? false : (raw[0] === "'" ? sv[2] : Number(raw)); }
      const dv = text.match(/desc:\s*'((?:\\.|[^'])*)'/);
      const desc = dv ? dv[1].replace(/\\'/g, "'").replace(/\s+/g, ' ').slice(0, 140) : '';
      out.push({ name: r.name, evolvable: r.evolvable, reason: r.reason, src: r.src, module: r.module, kind, value, desc });
    }
    return { rules: out, talker: { system: !!map.talker.system, retry: !!map.talker.retry } };
  }

  /* ---- the offline agent's scripted hypotheses (same as the Node loop) ---- */
  const offlineHypotheses = [
    { target: 'inertia_delta 2.0 → 1.75', note: 'loosen the over-strict dominance gate so a clear "she said" binds; honest stalls survive', edits: [{ kind: 'rule-value', rule: 'inertia_delta', value: 1.75 }] },
    { target: 'inertia_delta 1.75 → 1.6', note: 'push further — should over-correct and suppress an honest stall (a null)', edits: [{ kind: 'rule-value', rule: 'inertia_delta', value: 1.6 }] },
    { target: 'pronoun_resolution_floor 0.1 → 0.0', note: 'try to abolish abstention — the constitution must reject this', edits: [{ kind: 'rule-value', rule: 'pronoun_resolution_floor', value: 0 }] },
    { target: 'mass_weight 0.1 → 0.4', note: 'over-weight name mass — should regress binding', edits: [{ kind: 'rule-value', rule: 'mass_weight', value: 0.4 }] },
  ];

  /* ---- evaluate one candidate end-to-end (render → load → score → classify) ---- */
  async function evaluate({ pivotSrc, engineSrc, edits, nlp, data, baseline, cfg }) {
    const rendered = PATCH.renderEdits(engineSrc, edits);
    if (!rendered.ok) return { state: 'rejected-by-allowlist', surface: false, rejected: rendered.rejected, note: rendered.rejected.map(r => r.reason).join('; ') };
    let E;
    try { E = loadCandidate(pivotSrc, rendered.newSource, nlp); }
    catch (e) { return { state: 'broken', surface: false, diff: rendered.diff, note: 'candidate engine failed to load: ' + String(e.message || e) }; }
    const quality = await scoreQuality(E, data);
    const parity = await runParity(E, data);
    const qualityDelta = quality.composite - baseline.composite;
    const componentDeltas = {
      binding: quality.components.binding - baseline.components.binding,
      stall: quality.components.stall - baseline.components.stall,
      grounding: quality.components.grounding - baseline.components.grounding,
      integration: quality.components.integration - baseline.components.integration,
    };
    const cls = classify(parity.diffs, qualityDelta, cfg);
    return Object.assign({ diff: rendered.diff, quality, parity, qualityDelta, componentDeltas, touchedRegions: rendered.touchedRegions }, cls);
  }

  /* ---- the graph a text DEFines + what reading it RECurses (learns) ----
     Surfaced in the operators' own vocabulary so the experiment is legible:
     DEF (entities + relations the engine defines), SIG (speech), NUL (honest
     holds), REC (vocabulary it induced from this text — plastic neurons). */
  async function graphOf(E, text, id) {
    const doc = await E.parseDocument((id || 'doc') + '.txt', text, id || 'doc');
    const ev = doc._events || [];
    let entities = [];
    try { entities = (E.projectEntities(doc).entities || []).map(e => ({ name: e.name, type: e.type, gender: e.gender, mass: e.mass })); } catch (e) {}
    const speech = ev.filter(e => e.op === 'SIG' && e.speaker && e.speaker !== '?')
      .map(e => ({ at: e.sentence_idx, speaker: e.speaker, quote: (e.quote || '').replace(/\s+/g, ' ').slice(0, 64), how: e.attributed }));
    const defs = ev.filter(e => e.op === 'DEF')
      .map(e => ({ at: e.sentence_idx, target: e.target, path: e.path, value: e.value, reason: e.reason }));
    const merges = ev.filter(e => e.op === 'SYN' && e.method === 'gravity' && Array.isArray(e.sites))
      .map(e => ({ sites: e.sites }));
    const stalls = ev.filter(e => e.op === 'NUL' && e.reason && e.reason.indexOf('pronoun-stall') === 0)
      .map(e => ({ at: e.sentence_idx, surface: e.surface, competing: ((e.observed && e.observed.competing) || e.competing || []).slice(0, 3).map(c => c.siteName + ' ' + c.score) }));
    const recs = ev.filter(e => e.op === 'REC')
      .map(e => ({ target: e.target, action: e.action, value: e.new_value != null ? e.new_value : e.value, reason: e.reason }));
    let learned = [];
    try { learned = (E._learnedVerbs ? E._learnedVerbs() : []).slice(0, 60); } catch (e) {}
    const counts = ev.reduce((m, e) => (m[e.op] = (m[e.op] || 0) + 1, m), {});
    return { entities, speech, defs, merges, stalls, recs, learned, counts, sentenceTexts: doc.sentenceTexts || [], _doc: doc };
  }

  /* ---- query the graph (chat-against-the-graph, no vector store) ---- */
  function queryGraph(E, doc, question) {
    try { const a = E.answer(doc, question); return { text: a.text, audit: a.audit || null, cites: (a.cites || []).length }; }
    catch (e) { return { text: null, error: String(e.message || e) }; }
  }

  /* ---- prompt lab: the LOCAL model answers off the grounded graph ----
     Optimize how the on-device LLM is prompted. The engine builds the
     grounded context; the local model (window.EOLLM) phrases it under a
     candidate talker prompt; Claude grades the result. */
  async function localAnswer({ EOLLM, EOEngine, doc, question, mlcKey, sysOverride }) {
    let ctx = '';
    try { ctx = EOEngine.context(doc, question, 8) || ''; } catch (e) {}
    const answer = await EOLLM.phrase({ mlcKey, question, contextText: ctx, mode: 'grounded', task: null, grounded: true, depth: 1, sysOverride });
    return { answer: String(answer || '').trim(), contextChars: ctx.length };
  }
  // Claude (the user's key) grades the local model's answer for Claude-comparable
  // quality. The source is a single short doc/excerpt, capped — never the corpus.
  async function judgeAnswer({ key, model, source, question, answer, maxSourceChars }) {
    const cap = maxSourceChars || 3500;
    const src = source.length > cap ? source.slice(0, cap) + '\n…[truncated]' : source;
    const system = 'You are grading a small on-device language model\'s answer for "Claude-comparable" quality. It must read off the provided document only. Score 0.0–1.0, averaging three criteria each in [0,1]: (1) FAITHFUL — every claim traces to the source, nothing invented; (2) ANSWERS — actually addresses the question; (3) INTELLIGENT — clear, well-organized, the kind of answer a strong model gives. Respond with ONLY a JSON object {"score": NUMBER, "critique": SHORT, "claude_would": ONE_SENTENCE on what a top answer adds}.';
    const user = 'QUESTION: ' + question + '\n\nSOURCE DOCUMENT:\n' + src + '\n\nLOCAL MODEL ANSWER:\n' + (answer || '(empty)');
    const r = await callAnthropic({ key, model: model || 'claude-opus-4-8', system, messages: [{ role: 'user', content: user }], maxTokens: 700 });
    let j = null; try { const a = r.text.indexOf('{'), b = r.text.lastIndexOf('}'); j = JSON.parse(r.text.slice(a, b + 1)); } catch (e) {}
    return {
      score: j && typeof j.score === 'number' ? Math.max(0, Math.min(1, j.score)) : null,
      critique: j ? j.critique : (r.text || '').slice(0, 240),
      claudeWould: j ? j.claude_would : null,
      tokens: r.tokens,
    };
  }

  /* ---- the OBSERVE battery the live agent reads ---- */
  async function traceBattery(E, data) {
    const fx = data.fixtures || {};
    const out = [];
    for (const kind of ['binding', 'stalls', 'integration']) {
      out.push('## ' + kind + ' fixtures');
      for (const f of (fx[kind] || [])) {
        const doc = await E.parseDocument(f.id + '.txt', f.doc, f.id);
        const ev = doc._events || [];
        let people = [];
        try { people = (E.projectEntities(doc).entities || []).filter(e => e.type === 'person').map(e => e.name + '(' + (e.gender || '?') + ')'); } catch (e) {}
        const stalls = ev.filter(e => e.op === 'NUL' && e.reason && e.reason.indexOf('pronoun-stall') === 0)
          .map(e => { const comp = (e.observed && e.observed.competing) || e.competing; return 's' + e.sentence_idx + ' "' + (e.surface || '') + '"' + (comp ? ' {' + comp.slice(0, 3).map(c => c.siteName + ':' + c.score).join(' ') + '}' : ''); });
        const sigs = ev.filter(e => e.op === 'SIG').map(e => 's' + e.sentence_idx + '→' + e.speaker + '<' + (e.attributed || '') + '>');
        out.push('- ' + f.id + ' [' + (f.genre || '') + '] people: ' + people.join(', '));
        if (stalls.length) out.push('    stalls: ' + stalls.join('; '));
        if (sigs.length) out.push('    attributions: ' + sigs.join(' '));
      }
    }
    return out.join('\n');
  }

  /* ---- the live Anthropic agent, called DIRECTLY from the browser ----
     Uses the anthropic-dangerous-direct-browser-access header (CORS); the
     key the user typed stays in their tab and goes straight to Anthropic. */
  const AGENT_SYSTEM = [
    'You evolve a deterministic reading engine by proposing ONE small, testable change per turn.',
    'You may change ONLY the rules listed under "EVOLVABLE RULES" in the user message. Use their EXACT names — NEVER invent a rule name (an unknown name is rejected and wastes the turn). Everything else — the EVA checks, the grounder, citation binding, the operator vocabulary, parity, the golden snapshots, the quality fixtures — is the constitution and is rejected mechanically before any rerun.',
    'Make a SMALL change from the rule\'s CURRENT value shown in the list — a gentle nudge (roughly ±10–30%), never an extreme jump (e.g. do not slam a dominance ratio from 2.0 to 0.12). The values are sensitive; large swings break parity and collapse stall honesty.',
    'Do NOT repeat a change to a rule that already regressed or was rejected this run — read PRIOR ATTEMPTS and try a different rule or direction.',
    'Parity is a floor; strongly prefer changes that keep it clean. Stall honesty punishes suppressing honest "I don\'t know" stalls — never raise confidence by abolishing abstention.',
    'Respond with ONLY a JSON object: {"target": short label, "statement": one sentence, "rationale": why (grounded in the trace), "argument": why a human should accept it, "predicted_component": "binding"|"stall"|"grounding", "edits": [ ... ]}.',
    'Each edit is one of: {"kind":"rule-value","rule":NAME,"value":NUMBER_OR_BOOL}, {"kind":"rule-tokens-add","rule":NAME,"tokens":[...]}, {"kind":"rule-tokens-remove","rule":NAME,"tokens":[...]}, {"kind":"prompt-edit","slot":"system"|"retry","find":TEXT,"replace":TEXT}.',
  ].join('\n');

  async function callAnthropic(opts) {
    const body = { model: opts.model || 'claude-opus-4-8', max_tokens: opts.maxTokens || 2000, system: opts.system, messages: opts.messages };
    if (opts.thinking) body.thinking = { type: 'adaptive' };
    const resp = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-api-key': opts.key,
        'anthropic-version': '2023-06-01',
        'anthropic-dangerous-direct-browser-access': 'true',
      },
      body: JSON.stringify(body),
    });
    let j; try { j = await resp.json(); } catch (e) { throw new Error('bad response from Anthropic (HTTP ' + resp.status + ')'); }
    if (!resp.ok || (j && j.error)) throw new Error((j && j.error && j.error.message) || ('Anthropic HTTP ' + resp.status));
    const text = (j.content || []).filter(b => b.type === 'text').map(b => b.text).join('').trim();
    const u = j.usage || {};
    return { text, tokens: (u.input_tokens || 0) + (u.output_tokens || 0) };
  }

  function liveAgent(opts) {
    let tokens = 0, TOKEN_MAX = opts.tokenMax || 150000;
    return {
      provider: 'live',
      tokensUsed() { return tokens; },
      tokenMax() { return TOKEN_MAX; },
      exhausted() { return tokens >= TOKEN_MAX; },
      extend(extra) { TOKEN_MAX += (extra || opts.tokenMax || 150000); },
      async hypothesize({ battery, baseline, history }) {
        if (this.exhausted()) return null;
        const hist = (history || []).map(h => '- ' + (h.hyp ? h.hyp.target : '?') + ' → ' + h.result.state +
          (h.result.qualityDelta != null ? ' (Δ' + h.result.qualityDelta.toFixed(4) + ', parity ' + (h.result.parity ? (h.result.parity.clean ? 'clean' : h.result.parity.diffs + ' diffs') : 'n/a') + ')' : '') +
          (h.result.note ? ' — ' + h.result.note : '')).join('\n');
        const inv = (opts.rules || []).filter(r => r.evolvable).map(r => {
          const v = r.kind === 'list'
            ? '[' + (r.value || []).slice(0, 8).join(', ') + ((r.value || []).length > 8 ? ', …' : '') + ']'
            : String(r.value);
          return '- ' + r.name + ' = ' + v + (r.kind === 'list' ? ' (list — use rule-tokens-add / rule-tokens-remove)' : '') + (r.desc ? '  · ' + r.desc : '');
        }).join('\n');
        const user = [
          'CURRENT QUALITY composite ' + baseline.composite.toFixed(4) + ' — binding ' + baseline.components.binding.toFixed(3) + ', stall ' + baseline.components.stall.toFixed(3) + ', grounding ' + baseline.components.grounding.toFixed(3) + '.', '',
          'EVOLVABLE RULES — the ONLY rules you may change. Use these EXACT names; propose a small change from the current value:',
          inv || '(none provided)', '',
          'GRAPH TRACES (what the engine currently extracts — this compact summary is all you get, never the source text):',
          battery, '',
          (history && history.length) ? 'PRIOR ATTEMPTS THIS RUN (do NOT repeat a rejected, null, or regressed move — try a different rule or direction):\n' + hist : 'First hypothesis of the run.', '',
          'Propose ONE small change most likely to raise the composite while keeping parity clean. Return only the JSON object.',
        ].join('\n');
        const r = await callAnthropic({ key: opts.key, model: opts.model, system: AGENT_SYSTEM, messages: [{ role: 'user', content: user }], maxTokens: opts.maxTokens || 2000, thinking: opts.thinking });
        tokens += r.tokens;
        let h; try { const a = r.text.indexOf('{'), b = r.text.lastIndexOf('}'); h = JSON.parse(r.text.slice(a, b + 1)); } catch (e) { return null; }
        if (!h || !Array.isArray(h.edits) || !h.edits.length) return null;
        h.predicted = h.predicted_component || h.predicted;
        return h;
      },
    };
  }

  return {
    loadCandidate, scoreQuality, runParity, classify, evaluate,
    sampleExcerpts, scoreRange, evaluateFast,
    evolvableRules, renderEdits: (s, e) => PATCH.renderEdits(s, e),
    offlineHypotheses, traceBattery, liveAgent, callAnthropic,
    graphOf, queryGraph, localAnswer, judgeAnswer,
    sameName, normName, DEFAULT_WEIGHTS, INTEGRATION_STUB,
  };
});
