/* ============================================================
   evo/sandbox.browser.js — the evolution loop, IN THE BROWSER.

   The Node runner loads a candidate engine into a `vm`; the browser does
   the same thing with `new Function`: it evaluates the (patched) engine
   source against a fresh fake `window`, yielding a second, ISOLATED
   EOEngine the app's live engine never sees. So a candidate change can be
   run and scored client-side with no server — and any MAY-evolve target
   can be patched, not just the few live-tunable knobs.

   It reuses the SHARED constitution (window.EVO_ALLOWLIST / window.EVO_PATCH)
   so what may evolve is defined in exactly one place, and ports the
   deterministic scoring (2a binding, 2b stall honesty, 2d grounding) and
   the golden-parity snapshot. UMD: also requirable in Node for testing.

   Data (fixtures, golden, harness docs) is supplied by the host as
   window.EVO_SANDBOX_DATA (generated by evo/build-sandbox-data.js).
   ============================================================ */
(function (root, factory) {
  const AL = (typeof require !== 'undefined') ? require('./allowlist') : root.EVO_ALLOWLIST;
  const PATCH = (typeof require !== 'undefined') ? require('./patch') : root.EVO_PATCH;
  const api = factory(AL, PATCH);
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
  else root.EVO_SANDBOX = api;
})(typeof window !== 'undefined' ? window : globalThis, function (AL, PATCH) {
  'use strict';

  const DEFAULT_WEIGHTS = { binding: 0.30, stall: 0.30, grounding: 0.20, integration: 0.20 };
  const INTEGRATION_STUB = 0.70;
  const WIN_THRESHOLD = 0.01, JUSTIFIED = 0.03;

  /* ---- load a candidate engine from (patched) source, isolated ---- */
  function loadCandidate(pivotSrc, engineSrc, nlp, perf) {
    const fakeWindow = {};
    const performance = perf || (typeof window !== 'undefined' && window.performance) || { now: () => Date.now() };
    const fn = new Function('window', 'nlp', 'console', 'performance', (pivotSrc || '') + '\n;\n' + engineSrc);
    fn(fakeWindow, nlp, (typeof console !== 'undefined' ? console : { log() {} }), performance);
    if (!fakeWindow.EOEngine) throw new Error('candidate engine did not publish EOEngine');
    return fakeWindow.EOEngine;
  }

  /* ---- name normalization (mirrors engine-host) ---- */
  const TITLES = new Set(['prince', 'princess', 'count', 'countess', 'king', 'queen', 'lord', 'lady', 'mr', 'mrs', 'miss', 'ms', 'sir', 'dame', 'lieutenant', 'captain', 'colonel', 'major', 'general', 'admiral', 'emperor', 'empress', 'tsar', 'czar', 'duke', 'duchess', 'earl', 'baron', 'baroness', 'dr', 'prof', 'professor']);
  function normName(s) {
    let t = String(s || '').toLowerCase().replace(/['’]s\b/g, '').replace(/[^a-z0-9'’\s-]/g, ' ').replace(/\s+/g, ' ').trim();
    const w = t.split(' ').filter(Boolean);
    while (w.length > 1 && (TITLES.has(w[0]) || w[0] === 'the' || w[0] === 'a')) w.shift();
    return w.join(' ');
  }
  function sameName(a, b) {
    const na = normName(a), nb = normName(b);
    if (!na || !nb) return false;
    if (na === nb) return true;
    const sa = new Set(na.split(' ')), sb = new Set(nb.split(' '));
    const [small, big] = sa.size <= sb.size ? [sa, sb] : [sb, sa];
    for (const x of small) if (!big.has(x)) return false;
    return small.size > 0;
  }
  const wsNorm = (s) => String(s || '').replace(/\s+/g, ' ').trim().toLowerCase();
  function locate(sentenceTexts, locator) {
    const needle = wsNorm(locator); let best = -1, len = Infinity;
    for (let i = 0; i < sentenceTexts.length; i++) {
      const hay = wsNorm(sentenceTexts[i]);
      if (hay.includes(needle) && hay.length < len) { best = i; len = hay.length; }
    }
    return best;
  }

  /* ---- deterministic scoring (2a / 2b / 2d) ---- */
  async function scoreBinding(E, fixtures) {
    let correct = 0, total = 0; const detail = [];
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const sigs = (doc._events || []).filter(e => e.op === 'SIG').map(e => ({ at: e.sentence_idx, speaker: e.speaker, quote: (e.quote || '') }));
      for (const b of (fx.bindings || [])) {
        total++;
        const idx = locate(doc.sentenceTexts || [], b.sentence);
        const here = sigs.filter(s => s.at === idx);
        let sig = here[0];
        if (b.quote && here.length > 1) sig = here.find(s => wsNorm(s.quote).includes(wsNorm(b.quote))) || sig;
        const bound = sig && sig.speaker && sig.speaker !== '?' ? sig.speaker : null;
        const ok = bound != null && sameName(bound, b.referent);
        if (ok) correct++;
        detail.push({ fixture: fx.id, expected: b.referent, bound, ok });
      }
    }
    return { score: total ? correct / total : 1, correct, total, detail };
  }

  async function scoreStall(E, fixtures) {
    let TP = 0, FP = 0, FN = 0, TN = 0;
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const nulls = (doc._events || []).filter(e => e.op === 'NUL' && e.reason && e.reason.indexOf('pronoun-stall') === 0)
        .map(e => ({ at: e.sentence_idx, surface: e.surface }));
      for (const site of (fx.sites || [])) {
        const idx = locate(doc.sentenceTexts || [], site.sentence);
        const stalled = nulls.some(n => n.at === idx && (!site.surface || wsNorm(n.surface) === wsNorm(site.surface)));
        const should = site.expect === 'stall';
        if (should && stalled) TP++; else if (!should && stalled) FP++; else if (should && !stalled) FN++; else TN++;
      }
    }
    const p = (TP + FP) ? TP / (TP + FP) : 1, r = (TP + FN) ? TP / (TP + FN) : 1;
    const f1 = (p + r) ? 2 * p * r / (p + r) : 1;
    const score = (TP + FN) === 0 ? (TN + FP ? TN / (TN + FP) : 1) : f1;
    return { score, f1, precision: p, recall: r, TP, FP, FN, TN };
  }

  async function scoreGrounding(E, fixtures) {
    let sum = 0, n = 0; const detail = [];
    for (const fx of fixtures) {
      const doc = await E.parseDocument(fx.id + '.txt', fx.doc, fx.id);
      const q = fx.question || 'what is this about';
      let grounded = false, clean = true;
      try { const a = E.answer(doc, q); grounded = !!(a.audit && a.audit.grounded); } catch (e) {}
      try { clean = (E.inventedTerms(doc, q) || []).length === 0; } catch (e) {}
      const s = (grounded ? 0.5 : 0) + (clean ? 0.5 : 0);
      sum += s; n++; detail.push({ fixture: fx.id, grounded, clean, score: s });
    }
    return { score: n ? sum / n : 1, detail };
  }

  async function scoreQuality(E, data, weights) {
    const w = weights || (data.weights) || DEFAULT_WEIGHTS;
    const fx = data.fixtures || {};
    const binding = await scoreBinding(E, fx.binding || []);
    const stall = await scoreStall(E, fx.stalls || []);
    const grounding = await scoreGrounding(E, fx.integration || []);
    const integration = INTEGRATION_STUB; // browser sandbox: 2c is the deterministic stub (no API)
    const composite = w.binding * binding.score + w.stall * stall.score + (w.grounding || 0) * grounding.score + w.integration * integration;
    return { weights: w, composite, components: { binding: binding.score, stall: stall.score, grounding: grounding.score, integration }, binding, stall, grounding };
  }

  /* ---- golden parity (snapshot vs the committed golden) ---- */
  const round = (x) => Math.round(x * 1e6) / 1e6;
  function snapshotProse(E, doc, tag, QUERIES, ANSWERS) {
    const out = {};
    for (const q of QUERIES) {
      out['retrieve:' + q] = E.retrieve(doc, q, 6).map(s => ({ i: s.i, score: round(s.score), overlap: s.overlap }));
      out['refDoc:' + q] = E.referencesDoc(doc, q);
      out['hasGround:' + q] = E.hasGround(doc, q);
      out['context:' + q] = E.context(doc, q, 6);
      const a = E.answer(doc, q);
      out['answer:' + q] = { text: a.text, audit: a.audit, cites: a.cites || null };
      out['invented:' + q] = E.inventedTerms(doc, q);
    }
    for (const ans of ANSWERS) { const bc = E.bindCitations(doc, ans, 'q', 'factual'); out['bind:' + ans] = { text: bc.text, audit: bc.audit, cites: bc.cites }; }
    return out;
  }
  async function runParity(E, data) {
    const h = data.harness, golden = data.golden || {};
    const voss = await E.parseDocument('Voss.txt', h.VOSS, 'voss');
    const big = await E.parseDocument('big.txt', h.BIG, 'big');
    const cur = { voss: snapshotProse(E, voss, 'voss', h.QUERIES, h.ANSWERS), big: snapshotProse(E, big, 'big', h.QUERIES, h.ANSWERS) };
    let diffs = 0, total = 0; const examples = [];
    for (const tag of Object.keys(cur)) for (const key of Object.keys(cur[tag])) {
      total++;
      if (JSON.stringify(cur[tag][key]) !== JSON.stringify((golden[tag] || {})[key])) { diffs++; if (examples.length < 6) examples.push(tag + ' / ' + key); }
    }
    return { diffs, total, clean: diffs === 0, examples };
  }

  function classify(parityDiffs, qualityDelta, cfg) {
    cfg = cfg || {};
    const win = cfg.qualityWinThreshold != null ? cfg.qualityWinThreshold : WIN_THRESHOLD;
    const just = cfg.justifiedBreakThreshold != null ? cfg.justifiedBreakThreshold : JUSTIFIED;
    if (parityDiffs === 0) return qualityDelta >= win
      ? { state: 'clean-win', surface: true, note: 'pure tuning that did not move the snapshotted paths; mergeable on quality alone' }
      : { state: 'null', surface: false, note: 'clean parity but no quality gain' };
    return qualityDelta >= just
      ? { state: 'justified-break', surface: true, note: 'a real behavior change the quality gain justifies; requires a human golden recapture' }
      : { state: 'regression', surface: false, note: 'broke behavior without paying for it' };
  }

  /* ---- enumerate the evolvable + constitutional rules for the UI ---- */
  function evolvableRules(engineSrc) {
    const map = AL.buildRegionMap(engineSrc);
    const lines = map.lines;
    const out = [];
    for (const r of Object.values(map.rules)) {
      // read the current scalar value or list from the source slice
      let kind = 'other', value = null;
      const text = lines.slice(r.startLine - 1, r.endLine).join('\n');
      const sv = text.match(/value:\s*('([^']*)'|true|false|-?[\d.]+)/);
      const lv = text.match(/value:\s*\[([^\]]*)\]/);
      if (lv) { kind = 'list'; value = lv[1].split(',').map(s => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean); }
      else if (sv) { kind = 'scalar'; const raw = sv[1]; value = raw === 'true' ? true : raw === 'false' ? false : (raw[0] === "'" ? sv[2] : Number(raw)); }
      out.push({ name: r.name, evolvable: r.evolvable, reason: r.reason, src: r.src, module: r.module, kind, value });
    }
    return { rules: out, talker: { system: !!map.talker.system, retry: !!map.talker.retry } };
  }

  /* ---- the offline agent's scripted hypotheses (same as the Node loop) ---- */
  const offlineHypotheses = [
    { target: 'inertia_delta 2.0 → 1.75', note: 'loosen the over-strict dominance gate so a clear "she said" binds; honest stalls survive', edits: [{ kind: 'rule-value', rule: 'inertia_delta', value: 1.75 }] },
    { target: 'inertia_delta 1.75 → 1.6', note: 'push further — should over-correct and suppress an honest stall (a null)', edits: [{ kind: 'rule-value', rule: 'inertia_delta', value: 1.6 }] },
    { target: 'pronoun_resolution_floor 0.1 → 0.0', note: 'try to abolish abstention — the constitution must reject this', edits: [{ kind: 'rule-value', rule: 'pronoun_resolution_floor', value: 0 }] },
    { target: 'mass_weight 0.1 → 0.4', note: 'over-weight name mass — should regress binding', edits: [{ kind: 'rule-value', rule: 'mass_weight', value: 0.4 }] },
  ];

  /* ---- evaluate one candidate end-to-end (render → load → score → classify) ---- */
  async function evaluate({ pivotSrc, engineSrc, edits, nlp, data, baseline, cfg }) {
    const rendered = PATCH.renderEdits(engineSrc, edits);
    if (!rendered.ok) return { state: 'rejected-by-allowlist', surface: false, rejected: rendered.rejected, note: rendered.rejected.map(r => r.reason).join('; ') };
    const E = loadCandidate(pivotSrc, rendered.newSource, nlp);
    const quality = await scoreQuality(E, data);
    const parity = await runParity(E, data);
    const qualityDelta = quality.composite - baseline.composite;
    const componentDeltas = {
      binding: quality.components.binding - baseline.components.binding,
      stall: quality.components.stall - baseline.components.stall,
      grounding: quality.components.grounding - baseline.components.grounding,
      integration: quality.components.integration - baseline.components.integration,
    };
    const cls = classify(parity.diffs, qualityDelta, cfg);
    return Object.assign({ diff: rendered.diff, quality, parity, qualityDelta, componentDeltas, touchedRegions: rendered.touchedRegions }, cls);
  }

  return {
    loadCandidate, scoreQuality, runParity, classify, evaluate,
    evolvableRules, renderEdits: (s, e) => PATCH.renderEdits(s, e),
    offlineHypotheses, sameName, normName, DEFAULT_WEIGHTS, INTEGRATION_STUB,
  };
});
